services:
  database:
    image: postgres
    container_name: postgres-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - envs/database.env

  backend:
    container_name: django-app
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./:/code
      - /${STATIC_VOLUME_PATH}
      - /${MEDIA_VOLUME_PATH}
    env_file:
      - envs/.env.dev
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - database
    command: python manage.py runserver 0.0.0.0:${PORT}

volumes:
  postgres_data:
