services:
  database:
    image: postgres
    container_name: postgres-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - envs/database.env

  web:
    container_name: gunicorn
    build:
      context: ./
      dockerfile: docker/Dockerfile.prod
    env_file:
      - envs/.env.prod
    expose:
      - 8000
    depends_on:
      - database
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/apps_static
      - media_volume:/code/media

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/code/apps_static
      - media_volume:/code/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
