FROM python:3.12.5

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN mkdir apps_static
RUN mkdir media

COPY requirements.txt ./
COPY requirements-prod.txt ./

RUN pip install --no-cache-dir -r requirements-prod.txt

COPY . ./
